"""Shared publication plotting style for the KG-MMAI experiment package.

The manuscript uses Figures 1--10. Historical diagnostic plots generated by
Script 06 are retained as supplementary assets and are automatically redirected
away from the manuscript figure-number namespace.
"""

from __future__ import annotations

import itertools
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt

__author__ = "LIJUNHUA"

BASE = {
    "font.family": "sans-serif",
    "font.sans-serif": ["Liberation Sans", "DejaVu Sans"],
    "font.size": 9,
    "axes.titlesize": 10.5,
    "axes.titleweight": "semibold",
    "axes.labelsize": 9.5,
    "xtick.labelsize": 8.5,
    "ytick.labelsize": 8.5,
    "legend.fontsize": 8.5,
    "figure.titlesize": 12,
    "figure.dpi": 120,
    "savefig.dpi": 400,
    "savefig.bbox": "tight",
    "savefig.pad_inches": 0.06,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.linewidth": 0.8,
    "axes.edgecolor": "#3D3D3D",
    "axes.labelcolor": "#1A1A1A",
    "text.color": "#1A1A1A",
    "xtick.color": "#3D3D3D",
    "ytick.color": "#3D3D3D",
    "xtick.major.width": 0.8,
    "ytick.major.width": 0.8,
    "xtick.major.size": 3.2,
    "ytick.major.size": 3.2,
    "grid.color": "#D8D8D8",
    "grid.linewidth": 0.6,
    "legend.frameon": False,
    "figure.facecolor": "white",
    "axes.facecolor": "white",
}
mpl.rcParams.update(BASE)
mpl.rcParams["axes.unicode_minus"] = False

TYPE_COLORS = {
    "SYM": "#1B6C7F", "CAU": "#C4622D", "PRE": "#6D4C8C",
    "HER": "#4A7C59", "EFF": "#C9A227",
}
TYPE_LABELS = {
    "SYM": "Symptom", "CAU": "Cause", "PRE": "Prescription",
    "HER": "Herb", "EFF": "Effect",
}
REL_COLORS = {
    "CAUSES": "#C4622D", "HAS_EFFECT": "#C9A227", "CONTAINS": "#6D4C8C",
    "RELIEVES": "#4A7C59", "TREATS": "#1B6C7F",
}
MODEL_COLORS = {
    "TransE": "#4C6EA8", "DistMult": "#E0A458",
    "ComplEx": "#B5485D", "RotatE": "#4F9D8E",
}
INK = "#1A1A1A"
MUTED = "#7A7A7A"
FAINT = "#E8E8E8"
ACCENT = "#B5485D"

# These names belonged to Figures 6--8 in an earlier draft. In the final
# manuscript those figure numbers are reserved for the reviewer-requested
# annotation, ablation, and exact-baseline analyses.
LEGACY_REDIRECT = {
    "fig06_ranking_robustness": "supplementary/supp_A_ranking_robustness",
    "fig07_relation_difficulty": "supplementary/supp_B_relation_difficulty_legacy",
    "fig08_small_sample": "supplementary/supp_C_small_sample_precision",
}


def _normalise_stem(path_stem):
    path = Path(path_stem)
    replacement = LEGACY_REDIRECT.get(path.name)
    if replacement is None:
        path.parent.mkdir(parents=True, exist_ok=True)
        return path
    redirected = path.parent / replacement
    redirected.parent.mkdir(parents=True, exist_ok=True)
    print(f"  redirecting legacy figure {path.name} -> {redirected.name}")
    return redirected


def panel_tag(ax, letter, dx=-0.10, dy=1.045):
    ax.text(dx, dy, letter, transform=ax.transAxes, fontsize=11.5,
            fontweight="bold", va="top", ha="left", color=INK)


def tag(fig, letter, x, y):
    fig.text(x, y, letter, fontsize=11.5, fontweight="bold",
             va="top", ha="left", color=INK)


def hgrid(ax, axis="y"):
    ax.grid(axis=axis, linewidth=0.6, color="#E2E2E2", zorder=0)
    ax.set_axisbelow(True)


def check_overlaps(fig, tol=0.5, verbose=True):
    """Report intersecting visible Text bounding boxes after rendering."""
    fig.canvas.draw()
    renderer = fig.canvas.get_renderer()
    items = []
    for ax in fig.axes:
        if not ax.axison:
            continue
        legend_texts = set()
        legend = ax.get_legend()
        if legend:
            legend_texts.update(id(t) for t in legend.get_texts())
        ticks = set(id(t) for t in ax.get_xticklabels() + ax.get_yticklabels())
        artists = (
            ax.texts + [ax.title, ax.xaxis.label, ax.yaxis.label]
            + ax.get_xticklabels() + ax.get_yticklabels()
        )
        for text in artists:
            if id(text) in legend_texts:
                continue
            if id(text) in ticks:
                tx, ty = text.get_position()
                if text in ax.get_xticklabels():
                    lo, hi = sorted(ax.get_xlim())
                    if not (lo - 1e-9 <= tx <= hi + 1e-9):
                        continue
                else:
                    lo, hi = sorted(ax.get_ylim())
                    if not (lo - 1e-9 <= ty <= hi + 1e-9):
                        continue
            label = text.get_text().strip()
            if not label or not text.get_visible():
                continue
            try:
                bb = text.get_window_extent(renderer)
            except Exception:
                continue
            if bb.width > 0 and bb.height > 0:
                items.append((label, bb))
    for text in fig.texts:
        label = text.get_text().strip()
        if label and text.get_visible():
            items.append((label, text.get_window_extent(renderer)))

    hits = []
    for (s1, b1), (s2, b2) in itertools.combinations(items, 2):
        dx = min(b1.x1, b2.x1) - max(b1.x0, b2.x0)
        dy = min(b1.y1, b2.y1) - max(b1.y0, b2.y0)
        if dx <= tol or dy <= tol:
            continue
        if s1 == s2 and abs(b1.x0 - b2.x0) < 1.0 and abs(b1.y0 - b2.y0) < 1.0:
            continue
        hits.append((s1[:34], s2[:34], round(dx, 1), round(dy, 1)))

    if verbose:
        if hits:
            print(f"    !! {len(hits)} text overlap(s)")
            for hit in hits[:12]:
                print(f"       '{hit[0]}' x '{hit[1]}' ({hit[2]}x{hit[3]} px)")
        else:
            print("    no text overlaps")
    return hits


def save(fig, path_stem, formats=("png", "pdf")):
    stem = _normalise_stem(path_stem)
    for ext in formats:
        fig.savefig(stem.with_suffix(f".{ext}"), format=ext)
    plt.close(fig)
    print(f"  wrote {stem}.{'/'.join(formats)}")


def save_checked(fig, path_stem, formats=("png", "pdf")):
    """Render, report text collisions, and write publication PNG/PDF assets."""
    stem = _normalise_stem(path_stem)
    hits = check_overlaps(fig)
    for ext in formats:
        fig.savefig(stem.with_suffix(f".{ext}"), format=ext)
    plt.close(fig)
    print(f"  wrote {stem}.{'/'.join(formats)}" +
          ("  [OVERLAPS PRESENT]" if hits else ""))
    return hits
